[versions]
adsMobileSdk = "0.21.0-beta01"
agp = "8.6.1"
appcompat = "1.7.0"
# Using lifecycle-process version 2.8.0 or higher may cause a crash on launch, see
# https://stackoverflow.com/a/78795449.
lifecycleProcess = "2.8.7"
material = "1.12.0"
constraintlayout = "2.2.0"
navigationFragment = "2.8.6"
navigationUi = "2.8.6"
preference = "1.2.1"
lifecycleViewmodelAndroid = "2.8.6"
recyclerview = "1.4.0"

[libraries]
ads-mobile-sdk = { module = "com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk", version.ref = "adsMobileSdk" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
lifecycle-viewmodel-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycleViewmodelAndroid" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

